from dotenv import dotenv_values

env_values = dotenv_values()


TRASH_SERVER_API_HOST = env_values['TRASH_SERVER_API_HOST']
TRASH_SERVER_API_PORT = env_values['TRASH_SERVER_API_PORT']


# POSTGRES DATABASE
ACCESS_DATABASE_HOST_POSTGRES = env_values["ACCESS_DATABASE_HOST_POSTGRES"]
ACCESS_DATABASE_PORT_POSTGRES = env_values["ACCESS_DATABASE_PORT_POSTGRES"]
ACCESS_DATABASE_USERNAME_POSTGRES = env_values["ACCESS_DATABASE_USERNAME_POSTGRES"]
ACCESS_DATABASE_PASSWORD_POSTGRES = env_values["ACCESS_DATABASE_PASSWORD_POSTGRES"]
ACCESS_DATABASE_NAME_POSTGRES = env_values["ACCESS_DATABASE_NAME_POSTGRES"]
ACCESS_DATABASE_CONNECTION_COUNT_POSTGRES = 5


# REDIS DATABASE
ACCESS_DATABASE_HOST_REDIS = env_values["ACCESS_DATABASE_HOST_REDIS"]
ACCESS_DATABASE_PORT_REDIS = env_values["ACCESS_DATABASE_PORT_REDIS"]
ACCESS_DATABASE_USERNAME_REDIS = env_values["ACCESS_DATABASE_USERNAME_REDIS"]
ACCESS_DATABASE_PASSWORD_REDIS = env_values["ACCESS_DATABASE_PASSWORD_REDIS"]
ACCESS_DATABASE_NAME_REDIS = env_values["ACCESS_DATABASE_NAME_REDIS"]
ACCESS_DATABASE_CONNECTION_COUNT_REDIS = 5
